USE online_food_del;

-- summary querry
-- 1. Total Orders Per City
SELECT r.city,
    COUNT(o.order_id) AS total_orders
FROM orders o
JOIN restaurant r
    ON o.restaurant_id = r.restaurant_id
GROUP BY r.city
ORDER BY total_orders DESC;

-- 2. Revenue Generated By Each Food Item
SELECT
    m.item_name,
    SUM(m.price * od.quantity) AS total_revenue
FROM menu_item m
JOIN order_details od
    ON m.item_id = od.item_id
GROUP BY m.item_name
ORDER BY total_revenue DESC;

-- 1. Top 5 Spending Customers
SELECT c.customer_id,c.customer_name,
    SUM(m.price * od.quantity) AS total_spent
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_details od
    ON o.order_id = od.order_id
JOIN menu_item m
    ON od.item_id = m.item_id
GROUP BY c.customer_id, c.customer_name
ORDER BY total_spent DESC
LIMIT 5;

-- 2. Restaurant-wise Order Count
SELECT r.restaurant_id,r.rest_name,
    COUNT(o.order_id) AS total_orders
FROM restaurant r
JOIN orders o
    ON r.restaurant_id = o.restaurant_id
GROUP BY r.restaurant_id, r.rest_name
ORDER BY total_orders DESC;

-- 3. Average Order Value by City
SELECT r.city,
    ROUND(AVG(order_total),2) AS avg_order_value
FROM (
    SELECT o.order_id,o.restaurant_id,
        SUM(m.price * od.quantity) AS order_total
    FROM orders o
    JOIN order_details od
        ON o.order_id = od.order_id
    JOIN menu_item m
        ON od.item_id = m.item_id
    GROUP BY o.order_id, o.restaurant_id
) t
JOIN restaurant r
    ON t.restaurant_id = r.restaurant_id
GROUP BY r.city
ORDER BY avg_order_value DESC;
